#pragma config(Sensor, dgtl1,  Shooter,        sensorDigitalOut)
#pragma config(Motor,  port2,           leftFront,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightFront,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port4,           rightBack,     tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port5,           leftBack,      tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port6,           pewPew,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int min(int a,int b){
	if (a<b){ return a;}
	else{ return b;}
}

int max(int a,int b){
	if (a>b){ return a;}
	else{ return b;}
}

int pewSpeed = 0; //how fast Tejas wants the shooter to spin
bool shootOn = false; //if shooting is on
bool childLock = true;
task main(){
	/*
	How to drive:
		right side forward/back    -> right joystick forward + back
		left side forward/back     -> left joystick forward + back

	How to shoot:
		toggle shooting wheel on   -> button 7L
		toggle shooting wheel off  -> button 7R
		eject frisbee              -> upper right trigger (6U)

	*/

	while(1==1){
		//set driving wheels to 0 unless specified


		//on until turned off; no need to hold 7L

		if (vexRT[Btn8R]){
			childLock = false;
		} else if (vexRT[Btn7D]&&vexRT[Btn8L]&&!vexRT[Btn8D]){
			childLock = true;

		}
		if (childLock) {
			motor[leftBack] = vexRT[Ch3];
			motor[leftFront] = -vexRT[Ch3];
			motor[rightBack] = -vexRT[Ch2];
			motor[rightFront] = -vexRT[Ch2];
		}else {
		motor[leftFront] = 0;
		motor[rightFront] = 0;
		motor[rightBack] = 0;
		motor[leftBack] = 0;
	}
		if (vexRT[Btn7L]){
			shootOn = true;
		}
		if (vexRT[Btn7R]){
			shootOn = false;
		}

		if (shootOn){ //toggle shoot on
			wait1Msec(26);
			if (vexRT[Btn5U]){ //increase speed
				pewSpeed = min(pewSpeed+1,180);
			}else if (vexRT[Btn5D]){ //decrease speed
				pewSpeed = max(pewSpeed-1,0);
			}
			motor[pewPew] = -pewSpeed; //sets speed of shooter
			SensorValue[Shooter] = vexRT[Btn6U]; //shoot frisbee if 8R

		}else{ //toggle shoot off
	  	motor[pewPew] = 0;
		}
	}
}
