#pragma config(Sensor, dgtl1,  Shooter,        sensorDigitalOut)
#pragma config(Motor,  port2,           leftFront,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightFront,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port4,           rightBack,     tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port5,           leftBack,      tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port6,           pewPew,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int min(int a,int b){
//	if (a<b){ return a;}
//	else{ return b;}
//}

//int max(int a,int b){
//	if (a>b){ return a;}
//	else{ return b;}
//}

int pewSpeed = 0; //how fast Tejas wants the shooter to spin
bool shootOn = false; //if shooting is on
bool blockMove = false; //if operator desires to prevent movement and change in speed during shooting

task main(){

	while(1==1){

    if (vexRT[Btn7U]) {
			blockMove = true;
		}
		if (vexRT[Btn7D]) {
			blockMove = false;
		}

		if (!blockMove){
			motor[leftFront] = -vexRT[Ch3];
			motor[rightFront] = -vexRT[Ch2];
			motor[rightBack] = -vexRT[Ch2];
			motor[leftBack] = vexRT[Ch3];
		}else {
			motor[leftFront] = 0;
			motor[rightFront] = 0;
			motor[rightBack] = 0;
			motor[leftBack] = 0;
		}

		if (vexRT[Btn7L]){
			shootOn = true;
		}
		if (vexRT[Btn7R]){
			shootOn = false;
		}

		if (shootOn){
				wait1Msec(26);
				pewSpeed = 70;
		   	//if (vexRT[Btn6U] && !blockMove){ //increase speed

		    //pewSpeed = min(pewSpeed+1,180);

		  	//}else if (vexRT[Btn5U] && !blockMove){ //decrease speed

		  	//pewSpeed = max(pewSpeed-1,0);

				//}

			motor[pewPew] = -pewSpeed; //sets speed of shooter

			SensorValue[Shooter] = vexRT[Btn8R]; //shoot frisbee if 8R

		}
		else //shoot off
	  {
	  	motor[pewPew] = 0;
		}

	}
}
